name: 4testing multiarch-build

on: [push]
env:
    DOCKER_PATH: "/build/install/docker"
    REPO: "onlyoffice"
    DOCKERFILE: "Dockerfile.app"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
    concurrency: 
        group: ${{github.head_ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build 4testing
        run: |
          cd .${DOCKER_PATH}
          
          export DOCKER_TAG=$(echo "${GITHUB_REF_NAME}" | sed '/^release\b\|^hotfix\b/s/release.*\/\|hotfix.*\///')
          
          docker buildx bake -f build.yml \
          --set *.args.GIT_BRANCH=$GITHUB_REF_NAME \
          --set *.platform=linux/amd64 \
          --push

        shell: bash
