name: arm-build

on:
  push:
    branches: 
      - 'feature/test-tags'

env:
    DOCKER_PATH: "/build/install/docker"
    REPO: "lemmav"
    DOCKERFILE: "Dockerfile.arm"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64] #!
    concurrency: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2


      - name: Build 4testing
        run: |
          cd .${DOCKER_PATH}
          docker buildx build --platform=linux/arm64 --load -t ffmpeg -f Dockerfile.arm .
          
        shell: bash
